# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3a2785869ceb44485f4777dc3a4a5332c8ed5157678a5c75c8c60423d057fe73657a2fce0464a0e46ac0acdd5534c11cfec69e521dc5286ccdcefdeeb12c66

test:
  secret_key_base: 27e515ce5fe95ad91cf81e6d9216c25d55c22c46c14615176da3ba1da31b1869f76438d2683f67472116edd301dfafc5576aff2f867e9cd8f0ff04fe2357d9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
